### ISSUE TITLE
Resizing terminal window causes RuntimeError

### ISSUE THREAD

**Issue by tymat** [piotrmurach/tty#27]
**Steps**

1. Open iterm2
2. Run the progressbar example
3. Attempt to resize the iterm2 window

```
progressbar.rb:188:in `resize': Cannot resize finished progress bar (RuntimeError)
	from /Users/aeufemio/.rvm/gems/ruby-2.3.0@digixdao/gems/tty-progressbar-0.8.1/lib/tty/progressbar.rb:309:in `block in register_signals'
	from /Users/aeufemio/.rvm/gems/ruby-2.3.0@digixdao/gems/ethereum-0.4.95/lib/ethereum/transaction.rb:23:in `sleep'
	from /Users/aeufemio/.rvm/gems/ruby-2.3.0@digixdao/gems/ethereum-0.4.95/lib/ethereum/transaction.rb:23:in `wait_for_miner'
	from /Users/aeufemio/.rvm/gems/ruby-2.3.0@digixdao/gems/ethereum-0.4.95/lib/ethereum/contract.rb:205:in `block (3 levels) in build'
	from bin/deploy:139:in `<main>'
```

**Comment by piotrmurach** [comment]
Hi Anthony,

Thank you for using the library. It consists of independent components which get updated quite frequently and therefore may be out of sync with the latest `tty`. This is the case with `tty-progressbar` which had the above issue fixed recently in `v0.9.0`. If you could just install that, you should see the problem go away. In future if you find issues with specific component, please report it on its issue tracker.
