### ISSUE TITLE
Table rendering is not working

### ISSUE THREAD

**Issue by mad-raz** [piotrmurach/tty#28]
I have a simple script as part of a gem... the prompt, commands are working fine but rendering the tables doesn't work at all...

```rb
    TTY::Command.new(printer: :quiet).run('clear')
    TTY::Prompt.new.say("Updated at: #{Time.now}")
    table = TTY::Table.new ['header1','header2'], [['a1', 'a2'], ['b1', 'b2']]
    table.render :ascii
```
this doesn't output **only** the table to the terminal... but `table.to_s` outputs the following
```
"+-------+-------+\n|header1|header2|\n+-------+-------+\n|a1     |a2     |\n|b1     |b2     |\n+-------+-------+"
```

macOS Sierra (10.12.1)
ruby 2.3.2

**Comment by piotrmurach** [comment]
Hi Raz, thanks for giving tty a try! The components that you are looking at can also be used separately, e.i. you can install `tty-command`, `tty-prompt` and `tty-table` among many.

The idea behind table rendering is that the `render` or `to_s` converts the data into a string format. As is the case in your example, it is a perfectly formatted table. It is up to you what you want to do with it, one thing would be to print it to console like:

```ruby
puts table.render(:ascii)
```

**Comment by mad-raz** [comment]
sorry but how do I print the table to the tty ?  because
```
puts table.render(:ascii)
```
prints the following
```
"+-------+-------+\n|header1|header2|\n+-------+-------+\n|a1     |a2     |\n|b1     |b2     |\n+-------+-------+"
```
but I need it to print the table to the TTY correctly... not as 1 line

**Comment by piotrmurach** [comment]
The `render` or `to_s` messages return a string, nothing more or nothing else. So calling 
```ruby
table.render(:ascii)
```
will return actual string which is what you have in your example. Can you see the `\n` characters? These are line breaks. Any time console sees these it will render content after them on a new line, and hence a nice table. So my question to you would be, how do you render a string in Ruby to console?

**Comment by mad-raz** [comment]
Here is a screen shot
<img width="815" alt="screen shot 2016-11-27 at 23 38 52" src="https://cloud.githubusercontent.com/assets/347712/20652495/b7cbf9cc-b4fa-11e6-905b-e7fe44227cbf.png">

**Comment by piotrmurach** [comment]
Ok, I have no idea how you are preserving the string, my guess would be that you are escaping characters hence your `\\n` break line gets rendered as `\n` character, which in turn would explain the quotation marks in the output.

Running your code verbatim in irb session does the following

![screen shot 2016-11-27 at 22 40 12](https://cloud.githubusercontent.com/assets/444312/20652532/0bf74040-b4f3-11e6-9310-3c22a59a5221.png)

**Comment by mad-raz** [comment]
which bash version you have ?

**Comment by piotrmurach** [comment]
My bash version is `3.2.57(1)-release`. Could you please paste the code that you are actually using for creating and rendering the table. I'd like to see what you are exactly doing and maybe then we will solve this mystery.

**Comment by mad-raz** [comment]
yeah it's code used in the description of the issue (just added puts to table render)
and I found a solution to show it correctly using `Command.new.run('echo', table.render(:unicode))`
didn't work with :ascii cause the pipe is causing issues with the echo command

**Comment by piotrmurach** [comment]
Aha that makes sense, because `Command.new.run(cmd)` escapes characters, that would totally explain why it was directly rendering the string. Sorry if I sounded a bit patronising by I couldn't for the world understand why the simple code that you have pasted wouldn't work. It is not the first time `tty-table` was used, I use it for many other scripts etc....

**Comment by mad-raz** [comment]
sorry I didn't understand your last comment but the following code 
```rb
    command = TTY::Command.new(printer: :quiet)
    command.run('clear')
    TTY::Prompt.new.say("Updated at: #{Time.now}")

    table = TTY::Table.new ['header1','header2'], [['a1', 'a2'], ['b1', 'b2']]
    p 'using puts'
    p table.render(:unicode)
    p 'using command'
    command.run('echo', table.render(:unicode))

```
out puts the following
```
Updated at: 2016-11-28 00:06:41 +0100
"using puts"
"┌───────┬───────┐\n│header1│header2│\n├───────┼───────┤\n│a1     │a2     │\n│b1     │b2     │\n└───────┴───────┘"
"using command"
┌───────┬───────┐
│header1│header2│
├───────┼───────┤
│a1     │a2     │
│b1     │b2     │
└───────┴───────┘
```

**Comment by piotrmurach** [comment]
Why are you using the `Kernel.p` method? It simply calls `inspect` on Ruby string and prints to standard out without evaluating the actual string. When you want to print to console why don't you  use `puts` or `print`. Forget about `tty-table`, you can see your issue in the following simple example:

```ruby
multiline = "line1\nline2\nline3"
p multiline
# => "line1\nline2\nline3"
print multiline
# =>
# line1
# line2
# line3
``` 
You don't have to use `echo` at all. Simply print to standard out.

**Comment by mad-raz** [comment]
actually I didn't know that `Kernel.p` was not evaluating the string... thanks a lot for pointing this out
