### ISSUE TITLE
Installing gem doesn't provide binary (0.7.0)

### ISSUE THREAD

**Issue by mroach** [piotrmurach/tty#37]
I ran `gem install tty` to get the `teletype` binary. It didn't work. I dug into it and found that the `exe` dir is missing from the gem's installation dir.

I dug further and found that when you download the gem from rubygems.org, `tty.gemspec` is different from what's here on GitHub. Notable differences:

* `spec.bindir` is missing
* `spec.executables   = spec.files.grep(%r{^bin/}).map{ |f| File.basename(f) }` is used instead, which won't work since this project doesn't have a `bin` dir

Also, the `exe` dir is missing entirely when you download the gem from rubygems.org

So...did something go wrong in the gem cutting process that fouled-up `tty.gemspec`?

**Comment by piotrmurach** [comment]
Hi Mike,

Thanks for trying the gem out!

The `README.md` file is in line with the master branch. What you see there isn't released yet. I maintain and create quite few Ruby gems and find that the best (and for me the only) way to develop new code and stay on top of things is to write docs along side the code. If you wish to see `v0.7.0` you will need to select a tag.

I cannot tell you the exact date for the new release but I hope to get it done before the end of this month. In the meantime, I would appreciate if you could use master branch directly and hopefully contribute back and provide feedback.

I will keep this issue open in case others find it confusing as well. Sorry for the trouble!

**Comment by coisnepe** [comment]
Hey,

Any update on this issue?

**Comment by piotrmurach** [comment]
@coisnepe This is my highest priority now! However, I cannot give you an exact date but I'm working to release new `tty` version in March/April time. In the meantime I've been working on other tty packages. I have still few things to work on before `teletype` executable is in a good shape for release and a trip coming hence don't want to promise anything specific. I want to build a tool using `teletype` to ensure that it matches my needs and then I will be happy to cut a release.

**Comment by piotrmurach** [comment]
I'm speaking at RubyKaigi in Japan in about one hour and for this occasion I've released `v0.8.0` which includes the latest `teletype`! 🍾 🎆 Hope you like it! Any feedack greatly appreciated!
