### ISSUE TITLE
Feature request: add hyperlinks support

### ISSUE THREAD

**Issue by radarek** [piotrmurach/tty#55]
### Describe the problem

[Some terminals](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) support hyperlinks. You can try following code in terminal:

```
printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'
```

In iTerm it prints underlined `This is a link` and hovering it with `cmd` key I'm able to click on it and browser opens `http://example.com` link.

It would be nice to have a gem to:

* detect if this feature is supported by current terminal (npm library for reference https://github.com/jamestalmage/supports-hyperlinks)
* print hyperlink with custom text (npm library for reference https://www.npmjs.com/package/terminal-link)

**Comment by piotrmurach** [comment]
Hey Radek,

Thank you for making me aware of this! I think this is useful but I'm not 100% sure it deserves it's own gem, after all, it's a single line of code. But I will think about it. Maybe a single tty package that detects and implements links, let's see. However, there is a place I could totally use this feature in [tty-markdown](https://github.com/piotrmurach/tty-markdown#13-link)

**Comment by piotrmurach** [comment]
Hey @radarek I have goods news, your suggestion is now reality [tty-link](https://github.com/piotrmurach/tty-link). Enjoy!
