### ISSUE TITLE
Getting a success indicator in TTY::File.copy_file()

### ISSUE THREAD

**Issue by romera-github** [piotrmurach/tty#74]
### Describe the problem

I noticed that unlike TTY::File.copy_directory(), TTY::File.copy_file() does't return a value on success.
Would be possible that both methods behave similar?

### Steps to reproduce the problem
```
# Need of rescuing the method in order to know about the success 

begin
  TTY::File.copy_file(  ...  )
rescue
  success = false
  ...
else
  success = true
end
```

### Actual behaviour

```
result = TTY::File.copy_file()
# result == nil in both error and success
```

### Expected behaviour

Equivalent to its 'brother' method TTY::File.copy_directory()

### Describe your environment

* OS version:   macOS Big Sur 11.2
* Ruby version:   ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin20]
* TTY version:   tty-file-0.10.0

**Comment by piotrmurach** [comment]
Thank you for the report. 💯  Agreed. Sorry to be a pain but would you mind reposting this in the [tty-file](https://github.com/piotrmurach/tty-file) project issue tracker. And if you have time to submit PR I'd be most grateful.

**Comment by romera-github** [comment]
No problem. Moved the issue to tty-file - [Issue13](https://github.com/piotrmurach/tty-file/issues/13)

Sure, working on the PR
